### ISSUE TITLE
need Your Attention

### ISSUE THREAD

**Issue by SIN5ACOM** [zlounes/cosmos-autostaking#2]
installed your script "cosmos-autostaking" all done step by step as like in your readme, now have continually following ERROR:

------ REWARDS ------
failed to get from fields: Key MYKINODE not found------ DELEGATE ------
Balance: 906062943
Amount to delegate: 905962943
failed to get from fields: Key MYKINODE not foundspawn_id: spawn id exp4 not open
    while executing
"interact"
    (file "/root/cosmos-autostaking/delegate.exp" line 22)
------ SLEEP 300s ------

...how can be fixed this problem? 
Please need your help

**Comment by zakarialounes** [comment]
The NODE_HOME parameter of the kichain profile is relative to the current user. In your case root. Are you sure you have configured your validator with the user root? If not, then two options are available to you: 

- modify the NODE_HOME parameter of the kichain profile so that it uses the path of the correct user

or else

- run the cosmos-autostaking script with the same user as for your Kichain validator.

**Comment by SIN5ACOM** [comment]
ok, Node_Home -fixed! 
now new problem :)
------ SLEEP 300s ------
spawn ./delegate.sh /root/cosmos-autostaking/profiles/.kichain_profile
couldn't execute "./delegate.sh": no such file or directory
    while executing
"spawn ./delegate.sh $path"
    (file "/root/cosmos-autostaking/delegate.exp" line 8)
------ SLEEP 300s ------

**Comment by zlounes** [comment]
If you really insist on using another user than the one running the validator, then you have to adapt the whole profile to match the parameters.

**Comment by zlounes** [comment]
> ok, Node_Home -fixed!
> now new problem :)
> ------ SLEEP 300s ------
> spawn ./delegate.sh /root/cosmos-autostaking/profiles/.kichain_profile
> couldn't execute "./delegate.sh": no such file or directory
> while executing
> "spawn ./delegate.sh $path"
> (file "/root/cosmos-autostaking/delegate.exp" line 8)
> ------ SLEEP 300s ------

If you really insist on using another user than the one running the validator, then you have to adapt the whole profile to match the parameters.

**Comment by zakarialounes** [comment]
There may be a issue with the delegate.exp file that calls delegate.sh directly in the current dir. I'll check this and get back to you as soon as possible. In the meantime you must use the same user as the one running the validator.

**Comment by zakarialounes** [comment]
@SIN5ACOM Problem corrected, for more information feel free to consult the changes: 740e77ee388cbfbb0b81fdb067bf2a8d83986b84.

Feel free to back to us if you encounter any problems. Thanks for your feedback, muchly appreciated.
